### ISSUE TITLE
OSError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by ArkTuberGL** [mardelmariam/AS5600-RPi#2]
I get the following error: (sensor is connected)

`
Traceback (most recent call last):
  File "test.py", line 80, in <module>
    configureAS5600()
  File "test.py", line 53, in configureAS5600
    BUS.write_byte_data(I2C_MUX_ADDR, 0x00, I2C_MUX_DEVICE)
OSError: [Errno 121] Remote I/O error
`
(I copied the script to another file, so the traceback says "test.py")

**Comment by mardelmariam** [comment]
Hello, please check your i2c connections. That error happens when the SMBus instance doesn't detect any devices attached.

**Comment by ArkTuberGL** [comment]
Everything seems to be right. but i keep getting the error...
![image](https://user-images.githubusercontent.com/72625204/183086764-ad5b186a-9c74-4bff-912a-d750698f0abd.png)

**Comment by ArkTuberGL** [comment]
Oh... I just see that I'm not using a TCA9548A... Can you modify the script so that I can read the AS5600 directly?
